language: objective-c
osx_image: xcode10
script:
  - sudo gem install xcpretty
  - xcodebuild -workspace ooniprobe.xcworkspace/ -scheme ooniprobe CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty
