language: objective-c
osx_image: xcode9.4 # the current travis default
podfile: Podfile
before_install:
  - bundle install
  - pod repo update
  - pod install
script:
  - xcodebuild -workspace ooniprobe.xcworkspace/ -scheme ooniprobe CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty
  - xcodebuild test -workspace ooniprobe.xcworkspace/ -scheme OONIProbeUITests CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -destination 'platform=iOS Simulator,name=iPhone 8,OS=12.1'
